var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/gas/route.js")
R.c("server/chunks/[root-of-the-server]__20ov4shmgii3m._.js")
R.c("server/chunks/_1gbnh-4j-x3a8._.js")
R.c("server/chunks/1o_3_@noble_hashes_esm_1th7ltsp4p65b._.js")
R.c("server/chunks/node_modules__pnpm_1-goy_-sob-81._.js")
R.c("server/chunks/[root-of-the-server]__0007smw_fh63d._.js")
R.c("server/chunks/0xuy_@noble_curves_esm_secp256k1_0ft39-_e0r79q.js")
R.c("server/chunks/apps_web__next-internal_server_app_api_gas_route_actions_1bs_b125sai3n.js")
R.m(34847)
module.exports=R.m(34847).exports
