// GENERATED by scripts/gen-config.mjs from deployments/*.json. Do not edit.
// Vault state set by the constructor (no event carries it).
export interface VaultDefaults {
  keeper: string | undefined;
  tvlCap: bigint;
  performanceFeeBps: number;
}

export const VAULT_DEFAULTS: Record<number, VaultDefaults> = {
  10143: { keeper: "0x6e5008e79b3f6bcf314467c8b325b3784a9e9af4", tvlCap: 5000000000n, performanceFeeBps: 1000 },
};

/**
 * Every vault and venue ever deployed on the chain (current and archived deployments): holders of
 * outcome tokens that are protocol contracts, never users. The pre-v3 vaults' fills are not indexed,
 * so without this list their takers would inherit the old vault's split cost.
 */
export const SYSTEM_ADDRESSES: Record<number, string[]> = {
  10143: ["0xbeaf85d2682bad7ca09fd869037065350cf4a3b5", "0x28dbcf1631f51c9021d999b46e5d9439b4ed913c", "0xbe417d5d53725e60a937f2b2894972a7344a92cc", "0x68153506da3ab7d767c7462ed678d3804008c042", "0xcd2072443d37397dbea4e8eadbccfb8cb1f10748", "0xdf5958c9d759a97b7c3a9e49f8fb0924406698aa"],
};
