/**
 * Turns the raw run artefacts into the evidence tables:
 *   docs/evidence/phase-5/run-summary.md   coverage, quote age, violations, halts, errors, RPC load
 *   docs/evidence/phase-5/costs.md          cost per transaction kind, per re-quote and per day
 *
 * Usage: FROM=<ISO> TO=<ISO> tsx src/analyze.ts   (the window of the run; default: everything)
 * Inputs (all in docs/evidence/phase-5): metrics.jsonl, keeper.log, costs.jsonl, relay.log, driver.log
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const dir = resolve(here, "../../../docs/evidence/phase-5");
const from = process.env.FROM ? Date.parse(process.env.FROM) : 0;
const to = process.env.TO ? Date.parse(process.env.TO) : Number.POSITIVE_INFINITY;
const lines = (f: string) =>
  existsSync(resolve(dir, f))
    ? readFileSync(resolve(dir, f), "utf8")
        .split("\n")
        .filter(Boolean)
        .flatMap((l) => {
          try {
            return [JSON.parse(l) as Record<string, unknown>];
          } catch {
            return [];
          }
        })
    : [];

type Sample = { t: number; m: Record<string, number> };
const samples: Sample[] = lines("metrics.jsonl")
  .filter((r) => r.m)
  .map((r) => ({ t: Date.parse(r.t as string), m: r.m as Record<string, number> }))
  .filter((s) => s.t >= from && s.t <= to);
if (samples.length < 2) throw new Error("not enough metric samples in the window");
const first = samples[0] as Sample;
const last = samples[samples.length - 1] as Sample;
const delta = (k: string) => (last.m[k] ?? 0) - (first.m[k] ?? 0);
const sumDelta = (prefix: string) =>
  Object.keys(last.m)
    .filter((k) => k.startsWith(prefix))
    .reduce((a, k) => a + delta(k), 0);
const spanS = (last.t - first.t) / 1000;

// ---- coverage: every eligible market quoted
let covered = 0;
let withEligible = 0;
const gaps: { from: string; to: string; eligible: number; tradable: number; halted: number }[] = [];
let open: (typeof gaps)[number] | null = null;
for (const s of samples) {
  const e = s.m.keeper_eligible_markets ?? 0;
  const t = s.m.keeper_tradable_markets ?? 0;
  if (e === 0) {
    if (open) gaps.push(open);
    open = null;
    continue;
  }
  withEligible += 1;
  if (t >= e) {
    covered += 1;
    if (open) gaps.push(open);
    open = null;
  } else if (!open) {
    open = {
      from: new Date(s.t).toISOString(),
      to: new Date(s.t).toISOString(),
      eligible: e,
      tradable: t,
      halted: s.m.keeper_halted ?? 0,
    };
  } else open.to = new Date(s.t).toISOString();
}
if (open) gaps.push(open);

// ---- quote age (blocks): quantile from the cumulative histogram delta
const buckets = Object.keys(last.m)
  .map((k) => /^keeper_quote_age_blocks_bucket\{le="([^"]+)"\}$/.exec(k))
  .filter((m): m is RegExpExecArray => m !== null)
  .map((m) => ({
    le: m[1] === "+Inf" ? Number.POSITIVE_INFINITY : Number(m[1]),
    n: delta(m[0]),
  }))
  .sort((a, b) => a.le - b.le);
const ageCount = delta("keeper_quote_age_blocks_count");
const q = (p: number) => {
  if (ageCount === 0) return null;
  for (const b of buckets) if (b.n >= p * ageCount) return b.le;
  return null;
};

// ---- halts, from the keeper log
const klog = lines("keeper.log").filter(
  (r) => (r.time as number) >= from && (r.time as number) <= to,
);
const halts = klog
  .filter((r) => r.msg === "quotes pulled" && r.haltBlock !== undefined)
  .map((r) => ({
    at: new Date(r.time as number).toISOString(),
    reasons: (r.reasons as string[]).join("+"),
    triggerBlock: r.triggerBlock as string | null,
    haltBlock: r.haltBlock as string,
    blocks: r.blocks as number,
    hash: r.hash as string,
  }));
const unhandled = klog.filter((r) => /UNHANDLED|UNCAUGHT/.test(String(r.msg))).length;
const errors = Object.keys(last.m)
  .filter((k) => k.startsWith("keeper_errors_total"))
  .map((k) => ({ k, n: delta(k) }))
  .filter((x) => x.n > 0);
const fills = Object.keys(last.m)
  .filter((k) => k.startsWith("keeper_fills_total"))
  .map((k) => `${k.replace("keeper_fills_total", "")}: ${delta(k)}`);

const md: string[] = [];
md.push(`# Phase 5 testnet run: summary (TEST-ONLY prices)`);
md.push("");
md.push(
  `Window: ${new Date(first.t).toISOString()} to ${new Date(last.t).toISOString()} (${(spanS / 3600).toFixed(2)} h, ${samples.length} metric samples every ~15 s). Generated by \`scripts/keeper-live/src/analyze.ts\` from the files next to this one.`,
);
md.push("");
md.push(`| Measure | Value |`);
md.push(`|---|---|`);
md.push(`| Samples with an eligible market | ${withEligible} of ${samples.length} |`);
md.push(
  `| Samples with every eligible market tradable | ${covered} of ${withEligible} (${withEligible ? ((100 * covered) / withEligible).toFixed(1) : "n/a"} %) |`,
);
md.push(`| Executed orders (quote-age samples) | ${ageCount} |`);
md.push(`| Quote age p50 / p95 / p99 (blocks) | ${q(0.5)} / ${q(0.95)} / ${q(0.99)} |`);
md.push(
  `| Crossed, off-grid or out-of-bounds quotes | ${sumDelta("keeper_quote_violations_total")} |`,
);
md.push(`| Fills by outcome | ${fills.join(", ") || "none"} |`);
md.push(`| Pull-alls in the window | ${halts.length} |`);
md.push(`| Unhandled rejections / uncaught exceptions | ${unhandled} |`);
md.push(
  `| Errors by kind | ${errors.map((e) => `${e.k.replace("keeper_errors_total", "")}=${e.n}`).join(", ") || "none"} |`,
);
md.push(
  `| JSON-RPC calls per second (mean) | ${(sumDelta("keeper_rpc_requests_total") / spanS).toFixed(2)} |`,
);
md.push("");
if (gaps.length) {
  md.push(`## Intervals with an eligible market that was not tradable`);
  md.push("");
  md.push(`| From | To | Eligible | Tradable | Halted |`);
  md.push(`|---|---|---|---|---|`);
  for (const g of gaps)
    md.push(`| ${g.from} | ${g.to} | ${g.eligible} | ${g.tradable} | ${g.halted ? "yes" : "no"} |`);
  md.push("");
}
if (halts.length) {
  md.push(`## Pull-alls (blocks from the trigger to the halt transaction)`);
  md.push("");
  md.push(`| Time | Reasons | Trigger block | Halt block | Blocks | Tx |`);
  md.push(`|---|---|---|---|---|---|`);
  for (const h of halts)
    md.push(
      `| ${h.at} | ${h.reasons} | ${h.triggerBlock ?? "-"} | ${h.haltBlock} | ${h.blocks} | \`${h.hash}\` |`,
    );
  md.push("");
}
writeFileSync(resolve(dir, "run-summary.md"), `${md.join("\n")}\n`);
console.log(md.join("\n"));

// ---- costs
type Row = {
  atMs: number;
  kind: string;
  status: string;
  gasLimit: string;
  costWei: string;
  effectiveGasPriceWei: string;
  latencyMs: number;
};
const rows = (lines("costs.jsonl") as unknown as Row[]).filter(
  (r) => r.atMs >= from && r.atMs <= to,
);
if (rows.length) {
  const by = new Map<string, Row[]>();
  for (const r of rows) by.set(r.kind, [...(by.get(r.kind) ?? []), r]);
  const mon = (r: Row) => Number(r.costWei) / 1e18;
  const avg = (rs: Row[]) => rs.reduce((a, r) => a + mon(r), 0) / rs.length;
  const p95 = (rs: Row[]) => {
    const s = rs.map((r) => r.latencyMs).sort((a, b) => a - b);
    return s[Math.min(s.length - 1, Math.floor(0.95 * s.length))] ?? 0;
  };
  const price = rows.reduce((a, r) => a + Number(r.effectiveGasPriceWei), 0) / rows.length / 1e9;
  const c: string[] = [];
  c.push(`# Phase 5: what the keeper costs on Monad (testnet, measured)`);
  c.push("");
  c.push(
    `Window ${new Date(first.t).toISOString()} to ${new Date(last.t).toISOString()} (${(spanS / 3600).toFixed(2)} h). Every transaction the keeper sent is a line of \`costs.jsonl\`. Monad bills the gas **limit** (the keeper's limit is the estimate plus 15 %), at the effective gas price: mean ${price.toFixed(1)} gwei. 1 MON = 1e18 wei; MON has no price on testnet, so USD figures below take MON at an explicit, labelled assumption.`,
  );
  c.push("");
  c.push(`| Kind | Count | Avg gas limit | Avg cost (MON) | Total (MON) | p95 inclusion (ms) |`);
  c.push(`|---|---|---|---|---|---|`);
  for (const [k, rs] of [...by.entries()].sort(
    (a, b) => b[1].reduce((x, r) => x + mon(r), 0) - a[1].reduce((x, r) => x + mon(r), 0),
  ))
    c.push(
      `| ${k} | ${rs.length} | ${Math.round(rs.reduce((a, r) => a + Number(r.gasLimit), 0) / rs.length)} | ${avg(rs).toFixed(5)} | ${rs.reduce((a, r) => a + mon(r), 0).toFixed(4)} | ${p95(rs)} |`,
    );
  const total = rows.reduce((a, r) => a + mon(r), 0);
  const perDay = (total / spanS) * 86400;
  c.push("");
  c.push(
    `Total over the window: ${total.toFixed(4)} MON, ${rows.length} transactions. Extrapolated per day: **${perDay.toFixed(2)} MON** for this one TEST/USD series at 15-minute rounds.`,
  );
  writeFileSync(resolve(dir, "costs.md"), `${c.join("\n")}\n`);
}
