var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/markets/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__20dlt3r7bu--i._.js")
R.c("server/chunks/ssr/0yns_next_dist_esm_build_templates_app-page_00peivuiznjl5.js")
R.c("server/chunks/ssr/node_modules__pnpm_1op_uilih2zj0._.js")
R.c("server/chunks/ssr/1o_3_@noble_hashes_esm_1v1hmm3mr9_mp._.js")
R.c("server/chunks/ssr/0xuy_@noble_curves_esm_secp256k1_1of6xzkthntw4.js")
R.c("server/chunks/ssr/[root-of-the-server]__0950jsolnaiwk._.js")
R.c("server/chunks/ssr/apps_web_src_1als6_6xjh2l9._.js")
R.c("server/chunks/ssr/0yns_next_dist_1rv01_yxq-00c._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1e9359_p3n8c4._.js")
R.c("server/chunks/ssr/0yns_next_dist_client_components_1zfjmj5ftch9j._.js")
R.c("server/chunks/ssr/0yns_next_dist_client_components_builtin_forbidden_0hqa0y7-6tfv4.js")
R.c("server/chunks/ssr/0yns_next_dist_client_components_builtin_unauthorized_1ukafz5d7xmrj.js")
R.c("server/chunks/ssr/0yns_next_dist_client_components_builtin_global-error_09_6e9s_v5cc5.js")
R.c("server/chunks/ssr/apps_web__next-internal_server_app_markets_page_actions_0vwr44h0i3wn-.js")
R.m(13431)
module.exports=R.m(13431).exports
