/* global process, console */
// Generates the Envio config from deployments/<network>.json so addresses and start blocks have one
// source of truth. `node scripts/gen-config.mjs` writes config.yaml (testnet) and, when
// deployments/mainnet.json exists, config.mainnet.yaml. `--check` fails if a committed file is stale
// (used by make check-6). A local-chain config for the anvil run is written by
// `--local <addresses.json> <rpcUrl>` (output config.local.yaml, git-ignored, RPC source).
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "../..");

import { render } from "./config-lib.mjs";

function fromDeployment(path, header) {
  const d = JSON.parse(readFileSync(path, "utf8"));
  const v = d.vault;
  return render({
    chainId: d.chainId,
    header,
    factory: d.marketFactory,
    factoryBlock: d.deployBlock,
    vault: v.vault,
    venue: v.forwardVenue,
    vaultBlock: v.deployBlock,
  });
}

const HEADER = (src) =>
  `# yaml-language-server: $schema=./node_modules/envio/evm.schema.json\n# GENERATED by scripts/gen-config.mjs from ${src}. Do not edit; run \`pnpm --filter @converge/indexer gen:config\`.`;

const targets = [
  { file: "config.yaml", dep: "deployments/testnet.json", required: true },
  { file: "config.mainnet.yaml", dep: "deployments/mainnet.json", required: false },
];

if (process.argv.includes("--local")) {
  const i = process.argv.indexOf("--local");
  const addrs = JSON.parse(readFileSync(resolve(process.argv[i + 1]), "utf8"));
  const rpc = process.argv[i + 2];
  const out = render({
    chainId: addrs.chainId,
    header: "# LOCAL anvil config (generated, git-ignored). Data source: RPC, no HyperSync.",
    factory: addrs.factory,
    factoryBlock: addrs.factoryBlock,
    vault: addrs.vault,
    venue: addrs.venue,
    vaultBlock: addrs.vaultBlock,
    rpc,
  });
  writeFileSync(resolve(here, "../config.local.yaml"), out);
  console.log("wrote config.local.yaml");
  process.exit(0);
}

let bad = false;
for (const t of targets) {
  const depPath = resolve(root, t.dep);
  if (!existsSync(depPath)) {
    if (t.required) throw new Error(`${t.dep} missing`);
    console.log(`skip ${t.file}: ${t.dep} does not exist yet (nothing deployed on that chain)`);
    continue;
  }
  const out = fromDeployment(depPath, HEADER(t.dep));
  const target = resolve(here, "..", t.file);
  if (process.argv.includes("--check")) {
    const cur = existsSync(target) ? readFileSync(target, "utf8") : "";
    if (cur !== out) {
      console.error(`${t.file} is stale: run pnpm --filter @converge/indexer gen:config`);
      bad = true;
    }
  } else {
    writeFileSync(target, out);
    console.log(`wrote ${t.file}`);
  }
}
if (bad) process.exit(1);
else if (process.argv.includes("--check")) console.log("indexer config up to date");
