/* global process, console */
// Generates the Envio config and the per-chain constructor defaults from deployments/<network>.json
// so addresses, start blocks, keeper and TVL cap have one source of truth.
//   node scripts/gen-config.mjs           writes config.yaml (testnet), config.mainnet.yaml when
//                                         deployments/mainnet.json exists, and
//                                         src/lib/deployment-defaults.ts
//   node scripts/gen-config.mjs --check   fails if any committed file is stale (make check-6)
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { render, renderDefaults } from "./config-lib.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "../..");
const check = process.argv.includes("--check");

const HEADER = (src) =>
  `# yaml-language-server: $schema=./node_modules/envio/evm.schema.json\n# GENERATED by scripts/gen-config.mjs from ${src}. Do not edit; run \`pnpm --filter @converge/indexer gen:config\`.`;

const targets = [
  { file: "config.yaml", dep: "deployments/testnet.json", required: true },
  { file: "config.mainnet.yaml", dep: "deployments/mainnet.json", required: false },
];

let bad = false;
function emit(file, content) {
  const target = resolve(here, "..", file);
  if (check) {
    const cur = existsSync(target) ? readFileSync(target, "utf8") : "";
    if (cur !== content) {
      console.error(`${file} is stale: run pnpm --filter @converge/indexer gen:config`);
      bad = true;
    }
  } else {
    writeFileSync(target, content);
    console.log(`wrote ${file}`);
  }
}

const defaults = [];
for (const t of targets) {
  const depPath = resolve(root, t.dep);
  if (!existsSync(depPath)) {
    if (t.required) throw new Error(`${t.dep} missing`);
    console.log(`skip ${t.file}: ${t.dep} does not exist yet (nothing deployed on that chain)`);
    continue;
  }
  const d = JSON.parse(readFileSync(depPath, "utf8"));
  const v = d.vault;
  emit(
    t.file,
    render({
      chainId: d.chainId,
      header: HEADER(t.dep),
      factory: d.marketFactory,
      factoryBlock: d.deployBlock,
      vault: v.vault,
      venue: v.forwardVenue,
      vaultBlock: v.deployBlock,
    }),
  );
  defaults.push({ chainId: d.chainId, keeper: v.vaultKeeper, tvlCap: v.tvlCap });
}
emit(
  "src/lib/deployment-defaults.ts",
  renderDefaults(
    defaults,
    "// GENERATED by scripts/gen-config.mjs from deployments/*.json. Do not edit.\n// Vault state set by the constructor (no event carries it).",
  ),
);

if (bad) process.exit(1);
else if (check) console.log("indexer config and defaults up to date");
