/* global process, console */
// Builds the LOCAL indexer project used for the anvil run (never committed): a copy of src/ with the
// local chain's constructor defaults, a config whose data source is the local RPC (no HyperSync, no
// token), and symlinks to the schema and node_modules.
//   node scripts/local-project.mjs <addresses.json> <rpcUrl> [outDir=../.local-indexer/project]
import { cpSync, mkdirSync, readFileSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { render, renderDefaults } from "./config-lib.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const indexerDir = resolve(here, "..");
const [addrFile, rpc, outArg] = process.argv.slice(2);
if (!addrFile || !rpc)
  throw new Error("usage: local-project.mjs <addresses.json> <rpcUrl> [outDir]");
const out = resolve(outArg ?? resolve(indexerDir, "../.local-indexer/project"));
const a = JSON.parse(readFileSync(resolve(addrFile), "utf8"));

rmSync(resolve(out, "src"), { recursive: true, force: true });
mkdirSync(out, { recursive: true });
cpSync(resolve(indexerDir, "src"), resolve(out, "src"), { recursive: true });
writeFileSync(
  resolve(out, "src/lib/deployment-defaults.ts"),
  renderDefaults(
    [{ chainId: a.chainId, keeper: a.keeper, tvlCap: a.tvlCap }],
    "// LOCAL anvil defaults (generated by scripts/local-project.mjs).",
  ),
);
writeFileSync(
  resolve(out, "config.yaml"),
  render({
    chainId: a.chainId,
    header: "# LOCAL anvil config (generated, git-ignored). Data source: RPC, no HyperSync.",
    factory: a.factory,
    factoryBlock: a.factoryBlock,
    vault: a.vault,
    venue: a.venue,
    vaultBlock: a.vaultBlock,
    rpc,
  }),
);
for (const [name, target] of [
  ["schema.graphql", resolve(indexerDir, "schema.graphql")],
  ["node_modules", resolve(indexerDir, "node_modules")],
]) {
  rmSync(resolve(out, name), { recursive: true, force: true });
  symlinkSync(target, resolve(out, name));
}
writeFileSync(resolve(out, "package.json"), readFileSync(resolve(indexerDir, "package.json")));
writeFileSync(resolve(out, "tsconfig.json"), readFileSync(resolve(indexerDir, "tsconfig.json")));
console.log(`local indexer project written to ${out}`);
