/* global process, console */
// Generates src/abi/generated.ts from Foundry artifacts (contracts/out). Run after `forge build`.
// `node scripts/gen-abi.mjs --check` fails if the committed file is stale (used by make check-2).
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const out = resolve(here, "../../../contracts/out");
const target = resolve(here, "../src/abi/generated.ts");
const contracts = [
  ["MarketFactory", "marketFactoryAbi"],
  ["Market", "marketAbi"],
  ["OutcomeToken", "outcomeTokenAbi"],
  ["ChainlinkRoundResolver", "chainlinkRoundResolverAbi"],
  ["DataStreamsResolver", "dataStreamsResolverAbi"],
  ["IAggregatorV3", "aggregatorV3Abi"],
  ["SchedulerReceiver", "schedulerReceiverAbi"],
  ["MockAggregator", "mockAggregatorAbi"],
  ["MockERC20", "mockErc20Abi"],
];
let src = "// GENERATED by scripts/gen-abi.mjs from contracts/out. Do not edit.\n";
for (const [name, constName] of contracts) {
  const art = JSON.parse(readFileSync(resolve(out, `${name}.sol/${name}.json`), "utf8"));
  src += `\nexport const ${constName} = ${JSON.stringify(art.abi, null, 2)} as const;\n`;
}
if (process.argv.includes("--check")) {
  const current = readFileSync(target, "utf8");
  if (current !== src) {
    console.error("src/abi/generated.ts is stale: run `pnpm --filter @converge/sdk gen:abi`");
    process.exit(1);
  }
  console.log("abi up to date");
} else {
  writeFileSync(target, src);
  console.log(`wrote ${target}`);
}
