/**
 * Writes the Kuru evidence page from deployments/kuru-testnet.json: every transaction of every listed
 * round with its explorer link and gas limit (what Monad bills), and the cost per round.
 *
 *   pnpm --filter @converge/kuru report
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { root, STATE_PATH } from "./config";
import type { KuruState } from "./state";

const EXPLORER = "https://testnet.monadvision.com";
const GWEI = 102n; // Monad testnet gas price at the time of the runs (about 102 gwei)
const state = JSON.parse(readFileSync(STATE_PATH, "utf8")) as KuruState;
const mon = (gas: bigint) => Number((gas * GWEI * 1_000_000_000n) / 1_000_000_000_000n) / 1e6;

const out: string[] = [
  "# Kuru testnet evidence",
  "",
  `Generated by \`pnpm --filter @converge/kuru report\` from \`deployments/kuru-testnet.json\`. Maker: [\`${state.maker}\`](${EXPLORER}/address/${state.maker}). Kuru Router: \`${state.router}\`.`,
  "",
];
for (const r of Object.values(state.rounds)) {
  const gas = r.txs.reduce((a, t) => a + BigInt(t.gasLimit), 0n);
  out.push(
    `## Round ${new Date(r.start * 1000).toISOString().slice(0, 16)}Z (${r.status})`,
    "",
    `- Converge round: [\`${r.converge}\`](${EXPLORER}/address/${r.converge}), strike ${r.strike.toFixed(2)}`,
    `- UP token: [\`${r.up}\`](${EXPLORER}/address/${r.up})`,
    `- **Kuru market for the UP token**: [\`${r.kuru}\`](${EXPLORER}/address/${r.kuru})`,
    `- ${r.quotes} two-sided quotes posted; total gas limit ${gas.toLocaleString("en-US")} (about ${mon(gas).toFixed(2)} MON at ${GWEI} gwei)`,
    "",
    "| step | gas limit | transaction |",
    "|---|---:|---|",
    ...r.txs.map(
      (t) =>
        `| ${t.step} | ${Number(t.gasLimit).toLocaleString("en-US")} | [${t.hash.slice(0, 12)}…](${EXPLORER}/tx/${t.hash}) |`,
    ),
    "",
  );
}
mkdirSync(`${root}docs/evidence/kuru`, { recursive: true });
writeFileSync(`${root}docs/evidence/kuru/rounds.md`, out.join("\n") + "\n");
console.log(`wrote docs/evidence/kuru/rounds.md (${Object.keys(state.rounds).length} rounds)`);
